export const shoppingData = [
    // Make up
    {
        id: 1,
        title: 'OG MATTE LIQUID LIPSTICK',
        price:16,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/matte-lipstick-e1618454461421-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/lipstick-red-e1618456266346-370x463.jpg',
        key:'makeup',
        cate:'Make up',
        discount:'',
        sold:'',
        new:'',
        sku:'QQQQQ',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 2,
        title: 'COCO ROSE LIP TINT – CORAL',
        price:20,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/wet-lip-gloss-e1618455660983-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/wet-lip-gloss-3-e1618455402164-370x463.jpg',
        key:'makeup',
        cate:'Make up',
        new:'NEW',
        discount:'',
        sold:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 3,
        title: 'WEIGHTLESS LIPSTICK',
        prevPrice:65,
        price:30,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/lipstick-2-e1618456328818-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/01/Waterfall_Dip_Sarah_-370x463.jpg',
        key:'makeup',
        cate:'Make up',
        discount:'SALE 45%',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 4,
        title: 'NABELA NOOR LIP COCKTAIL KIT',
        price:16,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/eye-lip-set-e1618454718247-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/lip-cocktail-kit-e1618456362404-370x463.jpg',
        key:'makeup',
        cate:'Make up',
        sold:'SOLD OUT',
        disscount:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 5,
        title: 'MINT SEA SOAK',
        prevPrice:88,
        price:50,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/sea-soak-e1618456044915-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/polishing-wash-e1618456135737-370x463.jpg',
        key:'makeup',
        cate:'Make up',
        discount:'SALE 43%',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 6,
        title: 'HOLY GRAIL MATTE LIQUID LIPSTICK',
        price:22,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/coco-rose-lip-e1618454993250-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/cover-power-1-e1618454925615-370x463.jpg',
        key:'makeup',
        cate:'Make up',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 7,
        title: 'ANTIONXIDANT EYE SERUM',
        price:12,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/eye-serum-e1618456361200-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/rosehip-oil-e1618456072549-370x463.jpg',
        key:'makeup',
        cate:'Make up',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 8,
        title: 'SHOWER GEL',
        prevPrice:65,
        price:30,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/shower-gel-e1618456029741-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/body-scrub-e1618455244995-370x463.jpg',
        key:'makeup',
        cate:'Make up',
        discount:'SALE 54%',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 9,
        title: 'COCO ROSE LIP TINT – CORAL',
        price:10,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/coco-rose-lip-collection-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/mineral-cover-power-e1618456179489-370x463.jpg',
        key:'makeup',
        cate:'Make up',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },

    // Body
    {
        id: 10,
        title: 'WET LIP OIL GLOSS',
        price:27,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/lipstick-1-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/lipstick-370x463.jpg',
        key:'body',
        cate:'Body',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 11,
        title: 'BAYBY BUKI BRUSH',
        price:16,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/brush-buki-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/brush-370x463.jpg',
        key:'body',
        cate:'Body',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 12,
        title: 'VIRGIN BLUSH',
        price:24,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/power-4-370x463.jpg',
        hover : 'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/power-1-370x463.jpg',
        key:'body',
        cate:'Body',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 13,
        title: 'PRESSED MINERAL COVER FOUNDATION',
        price:27,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/power-1-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/foudation-1-370x463.jpg',
        key:'body',
        cate:'Body',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 14,
        title: 'MINERAL BRONZER 8G',
        price:15,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/Primer-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/cream-370x463.jpg',
        key:'body',
        cate:'Body',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 15,
        title: 'MINERAL CONCEALER 5G',
        price:22,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/power-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/foudation-1-370x463.jpg',
        key:'body',
        cate:'Body',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 16,
        title: 'AIRBRUSH MINERAL PRIMER',
        price:29,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/foudation-1-370x463.jpg',
        hover:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/power-370x463.jpg',
        key:'body',
        cate:'Body',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },

    // Tool & Brushes
    {
        id: 17,
        title: 'BAYBY BUKI BRUSH',
        price:15,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/Primer-370x463.jpg',
        key:'tool',
        cate:'Tool & Brushes',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 18,
        title: 'VIRGIN BLUSH',
        price:16,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/power-4-370x463.jpg',
        key:'tool',
        cate:'Tool & Brushes',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 19,
        title: 'PRESSED MINERAL COVER FOUNDATION',
        price:24,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/power-1-370x463.jpg',
        key:'tool',
        cate:'Tool & Brushes',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 20,
        title: 'WET LIP OIL GLOSS',
        price:16,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/cover-1-370x463.jpg',
        key:'tool',
        cate:'Tool & Brushes',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 21,
        title: 'WET LIP OIL GLOSS',
        price:24,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/blush-brush-1-370x463.jpg',
        key:'tool',
        cate:'Tool & Brushes',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    {
        id: 22,
        title: 'MINERAL BRONZER 8G',
        price:24,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/Primer-370x463.jpg',
        key:'tool',
        cate:'Tool & Brushes',
        disscount:'',
        sold:'',
        new:'',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
    // Holiday
    {
    id: 23,
    title: 'EVERYTHING PRIMER',
    price:12,
    img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/7-1-370x493.jpg',
    key:'lipstick',
    cate:'Lipstick',
    des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
},
{
    id: 24,
    title: 'THE BFF',
    price:82,
    img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/set-2-370x493.jpg',
    key:'lipstick',
    cate:'Lipstick',
    sku:'AAEERRR',
    des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
},
{
    id: 25,
    title: 'THE BFF',
    price:82,
    img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/B02-1-370x493.jpg',
    key:'lipstick',
    cate:'Lipstick',
    sku:'AAEERRR',
    des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
},
{
    id: 26,
    title: 'THE BFF',
    price:82,
    img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/B02-2-370x493.jpg',
    key:'lipstick',
    cate:'Lipstick',
    sku:'AAEERRR',
    des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
},
{
    id: 27,
    title: 'THE BFF',
    price:82,
    img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/B03-1-370x493.jpg',
    key:'lipstick',
    cate:'Lipstick',
    sku:'AAEERRR',
    des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
},
{
    id: 28,
    title: 'THE BFF',
    price:82,
    img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/B03-370x493.jpg',
    key:'lipstick',
    cate:'Lipstick',
    sku:'AAEERRR',
    des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
},
{
    id: 29,
    title: 'THE BFF',
    price:89,
    img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/B05-1-2-370x493.jpg',
    key:'lipstick',
    cate:'Lipstick',
    sku:'AAEERRR',
    des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
},

    {
        id: 30,
        title: 'THE G.O.A.T',
        price:32,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/set-1-370x493.jpg',
        key:'gift',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
  
    {
        id: 31,
        title: 'THE MILLENIAL',
        price:17,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/set-4-370x493.jpg',
        key:'gift',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
  
    {
        id: 32,
        title: 'THE BFF',
        price:32,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/set-3-370x493.jpg',
        key:'gift',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
  
    {
        id: 33,
        title: 'THE CRISKR',
        price:72,
        img:'http://ofeianht.jwsuperthemes.com/wp-content/uploads/2021/04/set-2-370x493.jpg',
        key:'gift',
        sku:'AAEERRR',
        des:'A smoothing, silicone-free primer that creates an even base for make-up application, while helping to extend wear.'
    },
  
]