export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const ADJUST_QUANTITY = "ADJUST_QUANTITY"
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM'
export const MINUS_FROM_CART = 'MINUS_FROM_CART'
export const COMPARE_FROM_CART = 'COMPARE_FROM_CART'
export const REMOVE_FROM_COMPARE = 'REMOVE_FROM_COMPARE'